apiVersion: batch/v1
kind: Job
metadata:
  name: useful-cookery-migrations
  labels:
    app: useful-cookery
    component: migrations
spec:
  template:
    metadata:
      labels:
        app: useful-cookery
        component: migrations
    spec:
      restartPolicy: Never
      containers:
        - name: migrations
          image: useful-cookery-migrations:latest
          imagePullPolicy: IfNotPresent
          # No need to specify command as it's set in the Dockerfile
          env:
            - name: DATABASE_TYPE
              valueFrom:
                configMapKeyRef:
                  name: useful-cookery-config
                  key: database.type
            - name: DATABASE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: useful-cookery-secrets
                  key: database.connection_string
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
  backoffLimit: 3
