package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"fmt"

	"github.com/carldunham/useful-cookery/internal/generated"
	"github.com/carldunham/useful-cookery/internal/graphql/model"
	model1 "github.com/carldunham/useful-cookery/internal/model"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	return r.register(ctx, input)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	return r.login(ctx, email, password)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (*model1.User, error) {
	return r.updateUser(ctx, input)
}

// CreateRecipe is the resolver for the createRecipe field.
func (r *mutationResolver) CreateRecipe(ctx context.Context, input model.RecipeInput) (*model1.Recipe, error) {
	return r.createRecipe(ctx, input)
}

// UpdateRecipe is the resolver for the updateRecipe field.
func (r *mutationResolver) UpdateRecipe(ctx context.Context, id string, input model.RecipeInput) (*model1.Recipe, error) {
	return r.updateRecipe(ctx, id, input)
}

// DeleteRecipe is the resolver for the deleteRecipe field.
func (r *mutationResolver) DeleteRecipe(ctx context.Context, id string) (bool, error) {
	return r.deleteRecipe(ctx, id)
}

// LikeRecipe is the resolver for the likeRecipe field.
func (r *mutationResolver) LikeRecipe(ctx context.Context, id string) (*model1.Recipe, error) {
	return r.likeRecipe(ctx, id)
}

// SaveRecipe is the resolver for the saveRecipe field.
func (r *mutationResolver) SaveRecipe(ctx context.Context, id string) (*model1.User, error) {
	return r.saveRecipe(ctx, id)
}

// UnsaveRecipe is the resolver for the unsaveRecipe field.
func (r *mutationResolver) UnsaveRecipe(ctx context.Context, id string) (*model1.User, error) {
	return r.unsaveRecipe(ctx, id)
}

// AddReview is the resolver for the addReview field.
func (r *mutationResolver) AddReview(ctx context.Context, recipeID string, rating int, comment *string) (*model1.Review, error) {
	return r.addReview(ctx, recipeID, rating, comment)
}

// UpdateReview is the resolver for the updateReview field.
func (r *mutationResolver) UpdateReview(ctx context.Context, id string, rating *int, comment *string) (*model1.Review, error) {
	return r.updateReview(ctx, id, rating, comment)
}

// DeleteReview is the resolver for the deleteReview field.
func (r *mutationResolver) DeleteReview(ctx context.Context, id string) (bool, error) {
	return r.deleteReview(ctx, id)
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, name string, description *string) (*model1.Category, error) {
	return r.createCategory(ctx, name, description)
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, id string, name *string, description *string) (*model1.Category, error) {
	return r.updateCategory(ctx, id, name, description)
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, id string) (bool, error) {
	return r.deleteCategory(ctx, id)
}

// Recipe is the resolver for the recipe field.
func (r *queryResolver) Recipe(ctx context.Context, id string) (*model1.Recipe, error) {
	return r.recipe(ctx, id)
}

// RecipeByOriginalID is the resolver for the recipeByOriginalId field.
func (r *queryResolver) RecipeByOriginalID(ctx context.Context, originalID string) (*model1.Recipe, error) {
	panic(fmt.Errorf("not implemented: RecipeByOriginalID - recipeByOriginalId"))
}

// Recipes is the resolver for the recipes field.
func (r *queryResolver) Recipes(ctx context.Context, filter *model.RecipeFilter, order *model.RecipeOrder, first *int, after *string, offset *int) (*model.RecipeConnection, error) {
	return r.recipes(ctx, filter, order, first, after, offset)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model1.User, error) {
	return r.me(ctx)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model1.User, error) {
	return r.user(ctx, id)
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*model1.Category, error) {
	return r.categories(ctx)
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, id string) (*model1.Category, error) {
	return r.category(ctx, id)
}

// SearchRecipes is the resolver for the searchRecipes field.
func (r *queryResolver) SearchRecipes(ctx context.Context, query string, first *int, after *string) (*model.RecipeConnection, error) {
	return r.searchRecipes(ctx, query, first, after)
}

// RecommendRecipes is the resolver for the recommendRecipes field.
func (r *queryResolver) RecommendRecipes(ctx context.Context, userID *string, availableIngredients []string, first *int, after *string) (*model.RecipeConnection, error) {
	return r.recommendRecipes(ctx, userID, availableIngredients, first, after)
}

// FindSubstitutes is the resolver for the findSubstitutes field.
func (r *queryResolver) FindSubstitutes(ctx context.Context, ingredientName string) ([]string, error) {
	return r.findSubstitutes(ctx, ingredientName)
}

// Difficulty is the resolver for the difficulty field.
func (r *recipeResolver) Difficulty(ctx context.Context, obj *model1.Recipe) (*model.SkillLevel, error) {
	return r.skillLevel(ctx, obj)
}

// SkillLevel is the resolver for the skillLevel field.
func (r *recipeResolver) SkillLevel(ctx context.Context, obj *model1.Recipe) (*model.SkillLevel, error) {
	return r.skillLevel(ctx, obj)
}

// DifficultyText is the resolver for the difficultyText field.
func (r *recipeResolver) DifficultyText(ctx context.Context, obj *model1.Recipe) (*string, error) {
	return r.difficultyText(ctx, obj)
}

// RecipeLikes is the resolver for the recipeLikes field.
func (r *subscriptionResolver) RecipeLikes(ctx context.Context, id string) (<-chan *int, error) {
	return r.Resolver.recipeLikes(ctx, id)
}

// NewReview is the resolver for the newReview field.
func (r *subscriptionResolver) NewReview(ctx context.Context, recipeID string) (<-chan *model1.Review, error) {
	return r.Resolver.newReview(ctx, recipeID)
}

// SkillLevel is the resolver for the skillLevel field.
func (r *userPreferencesResolver) SkillLevel(ctx context.Context, obj *model1.UserPreferences) (*model.SkillLevel, error) {
	return r.skillLevelPref(ctx, obj)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Recipe returns generated.RecipeResolver implementation.
func (r *Resolver) Recipe() generated.RecipeResolver { return &recipeResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

// UserPreferences returns generated.UserPreferencesResolver implementation.
func (r *Resolver) UserPreferences() generated.UserPreferencesResolver {
	return &userPreferencesResolver{r}
}

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type recipeResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type userPreferencesResolver struct{ *Resolver }
