linters:
  enable-all: true

  disable:
    - depguard
    - exhaustruct
    - godox # need my TODOs
    - gofumpt
    - nlreturn
    - tenv # Replaced by usetesting.
    - wsl
    - tagliatelle

  exclusions:
    rules:
      - path: cmd/cli
        linters:
          - forbidigo
      - path: cmd/migration
        linters:
          - forbidigo

linters-settings:
  goimports:
    local-prefixes: github.com/carldunham/useful-cookery

  varnamelen:
    # The minimum length of a variable name that is considered "long enough" and won't trigger the linter.
    min-name-length: 3
    # List of variable names that should be ignored completely.
    ignore-names:
      - db
      - tx
      - id
      - ok
      - err

  gci:
    custom-order: true
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(github.com/carldunham/useful-cookery) # Custom section: groups all imports with the specified Prefix.
      - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
      - dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
      - alias # Alias section: contains all alias imports. This section is not present unless explicitly enabled.
      - localmodule # Local module section: contains all local packages. This section is not present unless explicitly enabled.
