apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml
  - secrets.yaml

patchesStrategicMerge:
  - api-deployment-patch.yaml
  - ui-deployment-patch.yaml
  - migrations-job-patch.yaml

namespace: useful-cookery-local

commonLabels:
  environment: local
