apiVersion: batch/v1
kind: Job
metadata:
  name: useful-cookery-migrations
spec:
  template:
    spec:
      containers:
        - name: migrations
          image: useful-cookery-migrations:local
          imagePullPolicy: Never
