apiVersion: v1
kind: Secret
metadata:
  name: useful-cookery-secrets
type: Opaque
stringData:
  database.connection_string: "postgres://postgres:postgres@postgres:5432/useful-cookery?sslmode=disable"
  jwt.secret: "local-development-jwt-secret-replace-in-production"
  openai.api_key: "your-openai-api-key"
