// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"

	"github.com/carldunham/useful-cookery/internal/model"
)

type AuthPayload struct {
	Token string      `json:"token"`
	User  *model.User `json:"user"`
}

type ImageInput struct {
	URL    string  `json:"url"`
	Alt    *string `json:"alt,omitempty"`
	Width  *int    `json:"width,omitempty"`
	Height *int    `json:"height,omitempty"`
}

type IngredientInput struct {
	Name        string                 `json:"name"`
	Units       []*IngredientUnitInput `json:"units,omitempty"`
	Quantity    *float64               `json:"quantity,omitempty"`
	Unit        *string                `json:"unit,omitempty"`
	Preparation *string                `json:"preparation,omitempty"`
	Substitutes []string               `json:"substitutes,omitempty"`
	IsOptional  *bool                  `json:"isOptional,omitempty"`
}

type IngredientUnitInput struct {
	System string  `json:"system"`
	Value  float64 `json:"value"`
	Unit   string  `json:"unit"`
	IsMain bool    `json:"isMain"`
}

type Mutation struct {
}

type NutritionInfoInput struct {
	Calories *int     `json:"calories,omitempty"`
	Protein  *float64 `json:"protein,omitempty"`
	Carbs    *float64 `json:"carbs,omitempty"`
	Fat      *float64 `json:"fat,omitempty"`
	Fiber    *float64 `json:"fiber,omitempty"`
	Sugar    *float64 `json:"sugar,omitempty"`
	Sodium   *int     `json:"sodium,omitempty"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type RecipeConnection struct {
	Edges      []*RecipeEdge `json:"edges"`
	PageInfo   *PageInfo     `json:"pageInfo"`
	TotalCount int           `json:"totalCount"`
}

type RecipeEdge struct {
	Node   *model.Recipe `json:"node"`
	Cursor string        `json:"cursor"`
}

type RecipeFilter struct {
	Search      *string     `json:"search,omitempty"`
	OriginalID  *string     `json:"originalId,omitempty"`
	Categories  []string    `json:"categories,omitempty"`
	Cuisine     *string     `json:"cuisine,omitempty"`
	Difficulty  *SkillLevel `json:"difficulty,omitempty"`
	MaxPrepTime *int        `json:"maxPrepTime,omitempty"`
	Ingredients []string    `json:"ingredients,omitempty"`
	AuthorID    *string     `json:"authorID,omitempty"`
}

type RecipeInput struct {
	Title         string              `json:"title"`
	Description   string              `json:"description"`
	OriginalID    *string             `json:"originalId,omitempty"`
	CategoryIDs   []string            `json:"categoryIDs,omitempty"`
	Cuisine       *string             `json:"cuisine,omitempty"`
	PrepTime      *int                `json:"prepTime,omitempty"`
	CookTime      *int                `json:"cookTime,omitempty"`
	Servings      *int                `json:"servings,omitempty"`
	Difficulty    *SkillLevel         `json:"difficulty,omitempty"`
	Ingredients   []*IngredientInput  `json:"ingredients"`
	Steps         []*StepInput        `json:"steps"`
	NutritionInfo *NutritionInfoInput `json:"nutritionInfo,omitempty"`
	Tags          []string            `json:"tags,omitempty"`
	Images        []*ImageInput       `json:"images,omitempty"`
}

type RecipeOrder struct {
	Field     RecipeOrderField `json:"field"`
	Direction OrderDirection   `json:"direction"`
}

type RegisterInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type StepInput struct {
	OrderIndex   int         `json:"orderIndex"`
	Description  string      `json:"description"`
	Image        *ImageInput `json:"image,omitempty"`
	TimeEstimate *int        `json:"timeEstimate,omitempty"`
}

type Subscription struct {
}

type UpdateUserInput struct {
	Name        *string               `json:"name,omitempty"`
	Email       *string               `json:"email,omitempty"`
	Password    *string               `json:"password,omitempty"`
	Preferences *UserPreferencesInput `json:"preferences,omitempty"`
}

type UserPreferencesInput struct {
	DietaryRestrictions []string    `json:"dietaryRestrictions,omitempty"`
	FavoriteIngredients []string    `json:"favoriteIngredients,omitempty"`
	DislikedIngredients []string    `json:"dislikedIngredients,omitempty"`
	SkillLevel          *SkillLevel `json:"skillLevel,omitempty"`
	CuisinePreferences  []string    `json:"cuisinePreferences,omitempty"`
}

type OrderDirection string

const (
	OrderDirectionAsc  OrderDirection = "ASC"
	OrderDirectionDesc OrderDirection = "DESC"
)

var AllOrderDirection = []OrderDirection{
	OrderDirectionAsc,
	OrderDirectionDesc,
}

func (e OrderDirection) IsValid() bool {
	switch e {
	case OrderDirectionAsc, OrderDirectionDesc:
		return true
	}
	return false
}

func (e OrderDirection) String() string {
	return string(e)
}

func (e *OrderDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderDirection", str)
	}
	return nil
}

func (e OrderDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type RecipeOrderField string

const (
	RecipeOrderFieldCreatedAt RecipeOrderField = "CREATED_AT"
	RecipeOrderFieldTitle     RecipeOrderField = "TITLE"
	RecipeOrderFieldLikes     RecipeOrderField = "LIKES"
	RecipeOrderFieldRating    RecipeOrderField = "RATING"
)

var AllRecipeOrderField = []RecipeOrderField{
	RecipeOrderFieldCreatedAt,
	RecipeOrderFieldTitle,
	RecipeOrderFieldLikes,
	RecipeOrderFieldRating,
}

func (e RecipeOrderField) IsValid() bool {
	switch e {
	case RecipeOrderFieldCreatedAt, RecipeOrderFieldTitle, RecipeOrderFieldLikes, RecipeOrderFieldRating:
		return true
	}
	return false
}

func (e RecipeOrderField) String() string {
	return string(e)
}

func (e *RecipeOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RecipeOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RecipeOrderField", str)
	}
	return nil
}

func (e RecipeOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type SkillLevel string

const (
	SkillLevelBeginner     SkillLevel = "BEGINNER"
	SkillLevelIntermediate SkillLevel = "INTERMEDIATE"
	SkillLevelAdvanced     SkillLevel = "ADVANCED"
)

var AllSkillLevel = []SkillLevel{
	SkillLevelBeginner,
	SkillLevelIntermediate,
	SkillLevelAdvanced,
}

func (e SkillLevel) IsValid() bool {
	switch e {
	case SkillLevelBeginner, SkillLevelIntermediate, SkillLevelAdvanced:
		return true
	}
	return false
}

func (e SkillLevel) String() string {
	return string(e)
}

func (e *SkillLevel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SkillLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SkillLevel", str)
	}
	return nil
}

func (e SkillLevel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
