apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

patchesStrategicMerge:
  - api-deployment-patch.yaml
  - ui-deployment-patch.yaml

namespace: useful-cookery-prod

commonLabels:
  environment: production
